breaking main into functions

diff --git a/check-irods b/check-irods
--- a/check-irods
+++ b/check-irods
@@ -79,7 +79,7 @@ main()
     return 1
   fi
 
-  local logDir
+  local logDir=.
 
   eval set -- "$opts"
 
@@ -109,11 +109,6 @@ main()
     esac
   done
 
-  if [ -z "$logDir" ]
-  then
-    logDir=.
-  fi
-
   local clients=("$@")
 
   local testTime
@@ -121,28 +116,8 @@ main()
 
   local log
   log="$logDir"/irods-check-log-$(date --iso-8601 --date="$testTime").tsv
-
-  if [ ! -e "$logDir" ]
-  then
-    if ! mkdir --parents "$logDir"
-    then
-      return 1
-    fi
-  fi
-
-  if [ ! -s "$log" ]
-  then
-    if ! printf 'time\tclient\tresource\tstatus\n' > "$log"
-    then
-      return 1
-    fi
-  fi
-
-  for client in "${clients[@]}"
-  do
-    check_from_client "$client" \
-      1> >(log_statuses "$client" "$testTime") 2> >(display_errors "$client") &
-  done | sort --ignore-case --stable --key 2,2 >> "$log"
+  prep_log "$log"
+  check_from_clients "${clients[@]}" >> "$log"
 }
 
 
@@ -245,6 +220,18 @@ EOF
 }
 
 
+check_from_clients()
+{
+  local clients=("$@")
+
+  for client in "${clients[@]}"
+  do
+    check_from_client "$client" \
+      1> >(log_statuses "$client" "$testTime") 2> >(display_errors "$client") &
+  done | sort --ignore-case --stable --key 2,2
+}
+
+
 display_errors()
 {
   local client="$1"
@@ -271,6 +258,31 @@ log_statuses()
   do
     printf '%s\t%s\t%s\t%s\n' "$logTime" "$client" "$system" "$status"
   done
+}
+
+
+prep_log()
+{
+  local log="$1"
+
+  local logDir
+  logDir=$(dirname "$log")
+
+  if [ ! -e "$logDir" ]
+  then
+    if ! mkdir --parents "$logDir"
+    then
+      return 1
+    fi
+  fi
+
+  if [ ! -s "$log" ]
+  then
+    if ! printf 'time\tclient\tresource\tstatus\n' > "$log"
+    then
+      return 1
+    fi
+  fi
 }
 
 
