check_irods: default execution name
A default execution name will be used when script can't determine its actual name.

diff --git a/check_irods b/check_irods
--- a/check_irods
+++ b/check_irods
@@ -64,6 +64,7 @@ set -o errexit -o nounset -o pipefail
 
 readonly VERSION=8
 
+readonly DEFAULT_EXEC_NAME=check_irods
 readonly DEFAULT_PORT=1247
 
 # exit and return statuses
@@ -81,8 +82,10 @@ declare EXEC_NAME
 
 
 main() {
-	# TODO review possible error codes
-	EXEC_NAME="$(basename "$(realpath --canonicalize-missing "$0")")"
+	if ! EXEC_NAME="$(basename "$(realpath --canonicalize-missing "$0")")"; then
+		printf 'cannot determine executable name, using %s\n' "$DEFAULT_EXEC_NAME" >&2
+		EXEC_NAME="$DEFAULT_EXEC_NAME"
+	fi
 	readonly EXEC_NAME
 
 	declare -A argMap=(
