check_irods: grouped cmd line parsing logic

diff --git a/check_irods b/check_irods
--- a/check_irods
+++ b/check_irods
@@ -107,6 +107,10 @@ main() {
 		esac
 	done
 
+  if [[ "$#" -ge 1 ]]; then
+		argMap[ies]="$1"
+	fi
+
 	if [[ -n "${argMap[help]}" ]]; then
 		show_help
 		return 0
@@ -117,12 +121,11 @@ main() {
 		return 0
 	fi
 
-	if [ "$#" -lt 1 ]; then
+	if [[ -z "${argMap[ies]}" ]]; then
+		printf 'IES required\n' >&2
 		show_help >&2
 		return 1
 	fi
-
-	argMap[ies]="$1"
 
 	ping "${argMap[verbose]}" "${argMap[ies]}" "${argMap[port]}" "${argMap[service]}" "${argMap[zone]}"
 }
diff --git a/fsck-batch b/fsck-batch
--- a/fsck-batch
+++ b/fsck-batch
@@ -142,6 +142,29 @@ EOSSH
 export -f EXEC_ON_RS
 
 
+# build the ifsck call to check a replica
+# Arguments:
+#  filePath: The path to the replica on the resource server
+# Output:
+#  The output of the ifsck call
+# Returns:
+#  The exit status of the ifsck call
+CHECK_CMD() {
+	local filePath="$1"
+
+TODO substitute file path for file name in ifsck stdout and stderr
+  cat <<EOCMD
+if ! cd "\$(dirname '$filePath')"
+then
+	printf 'ERROR: fsckObj: %s does not exist\n' '$filePath' >&2
+	exit 184
+fi
+ifsck -K "\$(basename '$filePath')"
+EOCMD
+}
+export -f CHECK_CMD
+
+
 CHECK_OBJ() {
 	local resc="$1"
 	local objPath="$2"
@@ -151,7 +174,7 @@ CHECK_OBJ() {
 		if [[ "$rescHier" =~ ^${resc}(;.*)?$ ]]
 		then
 			local resp
-			resp="$(EXEC_ON_RS "$storeHost" "ifsck -K '$filePath'" 2>> "$ERR_LOG")"
+			resp="$(EXEC_ON_RS "$storeHost" "$(CHECK_CMD "$filePath")" 2>> "$ERR_LOG")"
 
 			local reason
 			if [[ "$resp" =~ size\.$ ]]
