check_irods: merged return code 3 into 2 for format_opts

diff --git a/check_irods b/check_irods
--- a/check_irods
+++ b/check_irods
@@ -62,6 +62,7 @@ main() {
 		[version]=''
 		[zone]='' )
 
+	# TODO handle return code 2
 	if ! map_args argMap "$@"; then
 		show_help >&2
 		return 1
@@ -90,16 +91,17 @@ main() {
 # Output:
 #  Any issues with the command line arguments will be written to stderr.
 # Return:
-#  It returns 0 on success and 1 on failure.
+#  It returns the following codes.
+#   0 on success
+#   1 if the command line arguments don't make sense
+#   2 if an internal error occured
 map_args() {
 	local mapVar="$1"
 	shift
 
+	# TODO inline opts
 	local opts
-	# TODO handle error code 1 separately from other format_opts error codes
-	if ! opts="$(format_opts "$@")"; then
-		return 1
-	fi
+	opts="$(format_opts "$@")"
 
 	eval set -- "$opts"
 
@@ -155,14 +157,24 @@ map_args() {
 #  It returns the following codes.
 #   0  on success
 #   1  if the command line options don't make sense
-#   2  if there is a programming error in this script
-#   3  if an internal error occurs in getopt
+#   2  if an internal error occured
 format_opts() {
+	set +o errexit
+
 	getopt \
 		--longoptions help,port:,service:,verbose,version,zone: \
 		--name "$EXEC_NAME" \
 		--options hP:S:VvZ: \
 		-- "$@"
+	local rc=$?
+
+	set -o errexit
+
+	if (( rc == 1 )); then
+		return 1
+	else
+		return 2
+	fi
 }
 
 
