localized all function vars

diff --git a/classify-repl-errors b/classify-repl-errors
--- a/classify-repl-errors
+++ b/classify-repl-errors
@@ -62,6 +62,7 @@ EOF
 
 main()
 {
+  local opts
   if ! opts=$(getopt --name "$ExecName" --options hv --longoptions help,version -- "$@")
   then
     exit_with_help
@@ -95,80 +96,105 @@ main()
     exit_with_help
   fi
 
-  readonly LogBase="$1"
+  local logBase="$1"
 
-  readonly ErrorsFile=$(mktemp)
-  readonly ReplErrorsFile=$(mktemp)
-  trap 'rm --force "$ErrorsFile" "$ReplErrorsFile"' EXIT
+  local errorsFile
+  errorsFile=$(mktemp)
+
+  local replErrorsFile
+  replErrorsFile=$(mktemp)
+
+  # shellcheck disable=SC2064
+  trap "rm --force '$errorsFile' '$replErrorsFile'" EXIT
 
   sed --quiet 's/.*ERROR: \([^\[].*$\)/\1/p' \
     | sed '/connectToRhost: readVersion to data.cyverse.org failed, msg=/d' \
-    | sort > "$ErrorsFile"
+    | sort > "$errorsFile"
 
-  readonly ErrCnt=$(wc --lines < "$ErrorsFile")
-  readonly CntWid=${#ErrCnt}
+  local errCnt
+  errCnt=$(wc --lines < "$errorsFile")
 
-  printf '%*d errors\n' "$CntWid" "$ErrCnt"
+  local cntWid=${#errCnt}
 
-  readonly ITCnt=$(split_out_class "$ErrorsFile" \
-                                   '^replUtil: invalid repl objType 0 for ' \
-                                   '' \
-                                   "$LogBase".invalid_types)
-  printf '%*d invalid object types\n' "$CntWid" "$ITCnt"
+  printf '%*d errors\n' "$cntWid" "$errCnt"
 
-  readonly SPECnt=$(split_out_class "$ErrorsFile" \
-                                    '^replUtil: srcPath \(.*\) does not exist$' \
-                                    '\1' \
-                                    "$LogBase".src_path_errors)
-  printf '%*d source path errors\n' "$CntWid" "$SPECnt"
+  local iTCnt
+  iTCnt=$(split_out_class "$errorsFile" \
+                          '^replUtil: invalid repl objType 0 for ' \
+                          '' \
+                          "$logBase".invalid_types)
 
-  split_out_class "$ErrorsFile" '^replUtil: repl error for ' '' "$ReplErrorsFile" > /dev/null
-  sort --output "$ReplErrorsFile" "$ReplErrorsFile"
+  printf '%*d invalid object types\n' "$cntWid" "$iTCnt"
 
-  readonly SHRLCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                          -4000 \
-                                          SYS_HEADER_READ_LEN_ERR \
-                                          "$LogBase".broken_conn)
-  printf '%*d broken connections\n' "$CntWid" "$SHRLCnt"
+  local sPECnt
+  sPECnt=$(split_out_class "$errorsFile" \
+                           '^replUtil: srcPath \(.*\) does not exist$' \
+                           '\1' \
+                           "$logBase".src_path_errors)
 
-  readonly SCLECnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                          -27000 \
-                                          SYS_COPY_LEN_ERR \
-                                          "$LogBase".short_file)
-  printf '%*d short files\n' "$CntWid" "$SCLECnt"
+  printf '%*d source path errors\n' "$cntWid" "$sPECnt"
 
-  readonly CRBPCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                          -116104 \
-                                          'SYS_SOCK_READ_ERR, Connection reset by peer' \
-                                          "$LogBase".connection_reset)
-  printf '%*d connections reset\n' "$CntWid" "$CRBPCnt"
+  split_out_class "$errorsFile" '^replUtil: repl error for ' '' "$replErrorsFile" > /dev/null
+  sort --output "$replErrorsFile" "$replErrorsFile"
 
-  readonly UCMCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                         -314000 \
-                                         USER_CHKSUM_MISMATCH \
-                                         "$LogBase".chksum_mismatches)
-  printf '%*d checksum mismatches\n' "$CntWid" "$UCMCnt"
+  local sHRLCnt
+  sHRLCnt=$(split_out_repl_class "$replErrorsFile" \
+                                 -4000 \
+                                 SYS_HEADER_READ_LEN_ERR \
+                                 "$logBase".broken_conn)
 
-  readonly UFOECnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                          -510002 \
-                                          'UNIX_FILE_OPEN_ERR, No such file or directory' \
-                                          "$LogBase".missing_file)
-  printf '%*d file open errors\n' "$CntWid" "$UFOECnt"
+  printf '%*d broken connections\n' "$cntWid" "$sHRLCnt"
 
-  readonly UnclassifiedReplErrCnt=$(wc --lines < "$ReplErrorsFile")
-  printf '%*d unclassified replication errors\n' "$CntWid" "$UnclassifiedReplErrCnt"
+  local sCLECnt
+  sCLECnt=$(split_out_repl_class "$replErrorsFile" \
+                                 -27000 \
+                                 SYS_COPY_LEN_ERR \
+                                 "$logBase".short_file)
 
-  if [ "$UnclassifiedReplErrCnt" -gt 0 ]
+  printf '%*d short files\n' "$cntWid" "$sCLECnt"
+
+  local cRBPCnt
+  cRBPCnt=$(split_out_repl_class "$replErrorsFile" \
+                                 -116104 \
+                                 'SYS_SOCK_READ_ERR, Connection reset by peer' \
+                                 "$logBase".connection_reset)
+
+  printf '%*d connections reset\n' "$cntWid" "$cRBPCnt"
+
+  local uCMCnt
+  uCMCnt=$(split_out_repl_class "$replErrorsFile" \
+                                -314000 \
+                                USER_CHKSUM_MISMATCH \
+                                "$logBase".chksum_mismatches)
+
+  printf '%*d checksum mismatches\n' "$cntWid" "$uCMCnt"
+
+  local uFOECnt
+  uFOECnt=$(split_out_repl_class "$replErrorsFile" \
+                                 -510002 \
+                                 'UNIX_FILE_OPEN_ERR, No such file or directory' \
+                                 "$logBase".missing_file)
+
+  printf '%*d file open errors\n' "$cntWid" "$uFOECnt"
+
+  local unclassifiedReplErrCnt
+  unclassifiedReplErrCnt=$(wc --lines < "$replErrorsFile")
+
+  printf '%*d unclassified replication errors\n' "$cntWid" "$unclassifiedReplErrCnt"
+
+  if [ "$unclassifiedReplErrCnt" -gt 0 ]
   then
-    mv "$ReplErrorsFile" "$LogBase".unclassified_repl_errors
+    mv "$replErrorsFile" "$logBase".unclassified_repl_errors
   fi
 
-  readonly UnclassifiedErrCnt=$(wc --lines < "$ErrorsFile")
-  printf '%*d unclassified errors\n' "$CntWid" "$UnclassifiedErrCnt"
+  local unclassifiedErrCnt
+  unclassifiedErrCnt=$(wc --lines < "$errorsFile")
 
-  if [ "$UnclassifiedErrCnt" -gt 0 ]
+  printf '%*d unclassified errors\n' "$cntWid" "$unclassifiedErrCnt"
+
+  if [ "$unclassifiedErrCnt" -gt 0 ]
   then
-    mv "$ErrorsFile" "$LogBase".unclassified_errors
+    mv "$errorsFile" "$logBase".unclassified_errors
   fi
 }
 
