grouped global code in main function

diff --git a/classify-repl-errors b/classify-repl-errors
--- a/classify-repl-errors
+++ b/classify-repl-errors
@@ -60,6 +60,119 @@ EOF
 }
 
 
+main()
+{
+  if ! opts=$(getopt --name "$ExecName" --options hv --longoptions help,version -- "$@")
+  then
+    exit_with_help
+  fi
+
+  eval set -- "$opts"
+
+  while true
+  do
+    case "$1" in
+      -h|--help)
+        show_help
+        exit 0
+        ;;
+      -v|--version)
+        show_version
+        exit 0
+        ;;
+      --)
+        shift
+        break
+        ;;
+      *)
+        exit_with_help
+        ;;
+    esac
+  done
+
+  if [ "$#" -lt 1 ]
+  then
+    exit_with_help
+  fi
+
+  readonly LogBase="$1"
+
+  readonly ErrorsFile=$(mktemp)
+  readonly ReplErrorsFile=$(mktemp)
+  trap 'rm --force "$ErrorsFile" "$ReplErrorsFile"' EXIT
+
+  sed --quiet 's/.*ERROR: \([^\[].*$\)/\1/p' \
+    | sed '/connectToRhost: readVersion to data.cyverse.org failed, msg=/d' \
+    | sort > "$ErrorsFile"
+
+  readonly ErrCnt=$(wc --lines < "$ErrorsFile")
+  readonly CntWid=${#ErrCnt}
+
+  printf '%*d errors\n' "$CntWid" "$ErrCnt"
+
+  readonly ITCnt=$(split_out_class "$ErrorsFile" \
+                                   '^replUtil: invalid repl objType 0 for ' \
+                                   '' \
+                                   "$LogBase".invalid_types)
+  printf '%*d invalid object types\n' "$CntWid" "$ITCnt"
+
+  readonly SPECnt=$(split_out_class "$ErrorsFile" \
+                                    '^replUtil: srcPath \(.*\) does not exist$' \
+                                    '\1' \
+                                    "$LogBase".src_path_errors)
+  printf '%*d source path errors\n' "$CntWid" "$SPECnt"
+
+  split_out_class "$ErrorsFile" '^replUtil: repl error for ' '' "$ReplErrorsFile" > /dev/null
+  sort --output "$ReplErrorsFile" "$ReplErrorsFile"
+
+  readonly SHRLCnt=$(split_out_repl_class "$ReplErrorsFile" \
+                                          -4000 \
+                                          SYS_HEADER_READ_LEN_ERR \
+                                          "$LogBase".broken_conn)
+  printf '%*d broken connections\n' "$CntWid" "$SHRLCnt"
+
+  readonly SCLECnt=$(split_out_repl_class "$ReplErrorsFile" \
+                                          -27000 \
+                                          SYS_COPY_LEN_ERR \
+                                          "$LogBase".short_file)
+  printf '%*d short files\n' "$CntWid" "$SCLECnt"
+
+  readonly CRBPCnt=$(split_out_repl_class "$ReplErrorsFile" \
+                                          -116104 \
+                                          'SYS_SOCK_READ_ERR, Connection reset by peer' \
+                                          "$LogBase".connection_reset)
+  printf '%*d connections reset\n' "$CntWid" "$CRBPCnt"
+
+  readonly UCMCnt=$(split_out_repl_class "$ReplErrorsFile" \
+                                         -314000 \
+                                         USER_CHKSUM_MISMATCH \
+                                         "$LogBase".chksum_mismatches)
+  printf '%*d checksum mismatches\n' "$CntWid" "$UCMCnt"
+
+  readonly UFOECnt=$(split_out_repl_class "$ReplErrorsFile" \
+                                          -510002 \
+                                          'UNIX_FILE_OPEN_ERR, No such file or directory' \
+                                          "$LogBase".missing_file)
+  printf '%*d file open errors\n' "$CntWid" "$UFOECnt"
+
+  readonly UnclassifiedReplErrCnt=$(wc --lines < "$ReplErrorsFile")
+  printf '%*d unclassified replication errors\n' "$CntWid" "$UnclassifiedReplErrCnt"
+
+  if [ "$UnclassifiedReplErrCnt" -gt 0 ]
+  then
+    mv "$ReplErrorsFile" "$LogBase".unclassified_repl_errors
+  fi
+
+  readonly UnclassifiedErrCnt=$(wc --lines < "$ErrorsFile")
+  printf '%*d unclassified errors\n' "$CntWid" "$UnclassifiedErrCnt"
+
+  if [ "$UnclassifiedErrCnt" -gt 0 ]
+  then
+    mv "$ErrorsFile" "$LogBase".unclassified_errors
+  fi
+}
+
+
 exit_with_help()
 {
   show_help >&2
@@ -109,112 +222,4 @@ split_out_repl_class()
 
 
 set -e
-
-if ! opts=$(getopt --name "$ExecName" --options hv --longoptions help,version -- "$@")
-then
-  exit_with_help
-fi
-
-eval set -- "$opts"
-
-while true
-do
-  case "$1" in
-    -h|--help)
-      show_help
-      exit 0
-      ;;
-    -v|--version)
-      show_version
-      exit 0
-      ;;
-    --)
-      shift
-      break
-      ;;
-    *)
-      exit_with_help
-      ;;
-  esac
-done
-
-if [ "$#" -lt 1 ]
-then
-  exit_with_help
-fi
-
-readonly LogBase="$1"
-
-readonly ErrorsFile=$(mktemp)
-readonly ReplErrorsFile=$(mktemp)
-trap 'rm --force "$ErrorsFile" "$ReplErrorsFile"' EXIT
-
-sed --quiet 's/.*ERROR: \([^\[].*$\)/\1/p' \
-  | sed '/connectToRhost: readVersion to data.cyverse.org failed, msg=/d' \
-  | sort > "$ErrorsFile"
-
-readonly ErrCnt=$(wc --lines < "$ErrorsFile")
-readonly CntWid=${#ErrCnt}
-
-printf '%*d errors\n' "$CntWid" "$ErrCnt"
-
-readonly ITCnt=$(split_out_class "$ErrorsFile" \
-                                 '^replUtil: invalid repl objType 0 for ' \
-                                 '' \
-                                 "$LogBase".invalid_types)
-printf '%*d invalid object types\n' "$CntWid" "$ITCnt"
-
-readonly SPECnt=$(split_out_class "$ErrorsFile" \
-                                  '^replUtil: srcPath \(.*\) does not exist$' \
-                                  '\1' \
-                                  "$LogBase".src_path_errors)
-printf '%*d source path errors\n' "$CntWid" "$SPECnt"
-
-split_out_class "$ErrorsFile" '^replUtil: repl error for ' '' "$ReplErrorsFile" > /dev/null
-sort --output "$ReplErrorsFile" "$ReplErrorsFile"
-
-readonly SHRLCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                        -4000 \
-                                        SYS_HEADER_READ_LEN_ERR \
-                                        "$LogBase".broken_conn)
-printf '%*d broken connections\n' "$CntWid" "$SHRLCnt"
-
-readonly SCLECnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                        -27000 \
-                                        SYS_COPY_LEN_ERR \
-                                        "$LogBase".short_file)
-printf '%*d short files\n' "$CntWid" "$SCLECnt"
-
-readonly CRBPCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                        -116104 \
-                                        'SYS_SOCK_READ_ERR, Connection reset by peer' \
-                                        "$LogBase".connection_reset)
-printf '%*d connections reset\n' "$CntWid" "$CRBPCnt"
-
-readonly UCMCnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                       -314000 \
-                                       USER_CHKSUM_MISMATCH \
-                                       "$LogBase".chksum_mismatches)
-printf '%*d checksum mismatches\n' "$CntWid" "$UCMCnt"
-
-readonly UFOECnt=$(split_out_repl_class "$ReplErrorsFile" \
-                                        -510002 \
-                                        'UNIX_FILE_OPEN_ERR, No such file or directory' \
-                                        "$LogBase".missing_file)
-printf '%*d file open errors\n' "$CntWid" "$UFOECnt"
-
-readonly UnclassifiedReplErrCnt=$(wc --lines < "$ReplErrorsFile")
-printf '%*d unclassified replication errors\n' "$CntWid" "$UnclassifiedReplErrCnt"
-
-if [ "$UnclassifiedReplErrCnt" -gt 0 ]
-then
-  mv "$ReplErrorsFile" "$LogBase".unclassified_repl_errors
-fi
-
-readonly UnclassifiedErrCnt=$(wc --lines < "$ErrorsFile")
-printf '%*d unclassified errors\n' "$CntWid" "$UnclassifiedErrCnt"
-
-if [ "$UnclassifiedErrCnt" -gt 0 ]
-then
-  mv "$ErrorsFile" "$LogBase".unclassified_errors
-fi
+main "$@"
