4.2.10: data-store-fix, works with any local zone now

diff --git a/data-store-fix b/data-store-fix
--- a/data-store-fix
+++ b/data-store-fix
@@ -168,10 +168,16 @@ fix() {
 	TempFiles+=("$(mktemp)")
 	local problems="${TempFiles[-1]}"
 
+	local zone
+	if ! zone="$(iquest '%s' "select ZONE_NAME where ZONE_TYPE = 'local'")"; then
+		printf 'Failed to determine local zone\n' >&2
+		return 1
+	fi
+
 	local cutoffTime
 	cutoffTime="$(date --iso-8601 --date "$age days ago")"
 
-	display_problems "$cutoffTime" | strip_noise > "$problems"
+	display_problems "$zone" "$cutoffTime" | strip_noise > "$problems"
 
 	trap 'if [[ "${FUNCNAME[0]-}" != main ]]; then return; fi' SIGINT SIGTERM
 
@@ -204,7 +210,8 @@ check_existing_instance() {
 
 
 display_problems() {
-	local cutoffTime="$1"
+	local zone="$1"
+	local cutoffTime="$2"
 
 	local cutoffTS
 	cutoffTS="$(date --date="$cutoffTime" '+0%s')"
@@ -230,15 +237,14 @@ CREATE TEMPORARY TABLE coll_perm_probs AS
 SELECT coll_id
 FROM r_coll_main AS c
 WHERE NOT EXISTS (SELECT * FROM owned_by_rodsadmin AS o WHERE o.object_id = c.coll_id)
-	AND c.coll_name LIKE '/iplant/%/%' AND c.coll_type != 'linkPoint' AND c.create_ts < '$cutoffTS';
+	AND c.coll_name LIKE '/$zone/%/%' AND c.coll_type != 'linkPoint' AND c.create_ts < '$cutoffTS';
 CREATE INDEX idx_coll_perm_probs ON coll_perm_probs(coll_id);
 
--- This may overestimate the number of problems, since it may find objects not in the iplant zone.
 $(inject_debug_msg creating data_perm_probs)
 CREATE TEMPORARY TABLE data_perm_probs AS
 SELECT DISTINCT data_id
 FROM r_data_main AS d JOIN r_coll_main AS c ON c.coll_id = d.coll_id
-WHERE c.coll_name LIKE '/iplant/%'
+WHERE c.coll_name LIKE '/$zone/%'
 	AND NOT EXISTS (SELECT * FROM owned_by_rodsadmin AS o WHERE o.object_id = d.data_id)
 	AND d.create_ts < '$cutoffTS';
 CREATE INDEX idx_data_perm_probs ON data_perm_probs(data_id);
@@ -254,12 +260,12 @@ $(inject_debug_msg creating coll_uuid_probs)
 CREATE TEMPORARY TABLE coll_uuid_probs (coll_id, uuid_count) AS
 SELECT c.coll_id, COUNT(u.object_id)
 FROM r_coll_main AS c LEFT JOIN uuid_attrs AS u ON u.object_id = c.coll_id
-WHERE c.coll_name LIKE '/iplant/%' AND c.coll_type != 'linkPoint' AND c.create_ts < '$cutoffTS'
+WHERE c.coll_name LIKE '/$zone/%' AND c.coll_type != 'linkPoint' AND c.create_ts < '$cutoffTS'
 GROUP BY c.coll_id
 HAVING COUNT(u.object_id) != 1;
 CREATE INDEX idx_coll_uuid_probs ON coll_uuid_probs (coll_id);
 
--- This may overestimate the number of problems, since it may find objects not in the iplant zone.
+-- This may overestimate the number of problems, since it may find objects not in the local zone.
 $(inject_debug_msg creating data_uuid_probs)
 CREATE TEMPORARY TABLE data_uuid_probs (data_id, uuid_count) AS
 SELECT DISTINCT d.data_id, COUNT(u.object_id)
@@ -270,7 +276,7 @@ GROUP BY d.data_id, d.data_repl_num
 HAVING COUNT(u.object_id) != 1;
 CREATE INDEX idx_data_uuid_probs ON data_uuid_probs(data_id);
 
--- This may overestimate the number of problems, since it may find objects not in the iplant zone.
+-- This may overestimate the number of problems, since it may find objects not in the local zone.
 $(inject_debug_msg creating data_checksum_probs)
 CREATE TEMPORARY TABLE data_chksum_probs AS
 SELECT DISTINCT data_id
@@ -288,7 +294,7 @@ SELECT
 	REPLACE(REPLACE(coll_name, E'\\\\', E'\\\\\\\\'), E'\\n', E'\\\\n')  AS "Collection"
 FROM r_coll_main AS c
 WHERE coll_id IN (SELECT * FROM coll_perm_probs UNION SELECT coll_id FROM coll_uuid_probs)
-	AND coll_name LIKE '/iplant/%'
+	AND coll_name LIKE '/$zone/%'
 	AND coll_type != 'linkPoint'
 	AND create_ts < '$cutoffTS'
 ORDER BY create_ts;
@@ -306,7 +312,7 @@ SELECT
 	REPLACE(REPLACE(c.coll_name || '/' || d.data_name, E'\\\\', E'\\\\\\\\'), E'\\n', E'\\\\n')
 		AS "Data Object"
 FROM r_coll_main AS c JOIN r_data_main AS d ON d.coll_id = c.coll_id
-WHERE c.coll_name LIKE '/iplant/%'
+WHERE c.coll_name LIKE '/$zone/%'
 	AND d.create_ts < '$cutoffTS'
 	AND d.data_id IN (
 		SELECT * FROM data_perm_probs
