repl: wrapped subshell executions in quotes

diff --git a/repl b/repl
--- a/repl
+++ b/repl
@@ -63,8 +63,8 @@ export TIMEDOUT=3
 readonly DEFAULT_AGE=1
 readonly DEFAULT_MAX_THREADS=16
 readonly DEFAULT_PROC_MULT=1
-readonly EXEC_PATH=$(readlink --canonicalize "$0")
-readonly EXEC_NAME=$(basename "$EXEC_PATH")
+readonly EXEC_PATH="$(readlink --canonicalize "$0")"
+readonly EXEC_NAME="$(basename "$EXEC_PATH")"
 readonly LOG=3
 
 
@@ -110,7 +110,7 @@ main() {
 		fi
 	fi
 
-  if [[ -n "${optMap[dest-resc]}" && "${optMap[src-resc]}" == "${optMap[dest-resc]}" ]]
+	if [[ -n "${optMap[dest-resc]}" && "${optMap[src-resc]}" == "${optMap[dest-resc]}" ]]
 	then
 		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
 		    "${optMap[dest-resc]}" "${optMap[src-resc]}" \
@@ -133,7 +133,7 @@ main() {
 	eval "exec $LOG>&1"
 
 	local objList
-	objList=$(mktemp)
+	objList="$(mktemp)"
 
 	trap 'finish "$?" '"'$objList'" EXIT
 
@@ -172,7 +172,7 @@ resolve_opts() {
 	shift
 
 	local opts
-	if ! opts=$(format_opts "$@")
+	if ! opts="$(format_opts "$@")"
 	then
 		return 1
 	fi
@@ -235,7 +235,7 @@ resolve_opts() {
 				break
 				;;
 			*)
-  			printf 'INTERNAL ERROR: Failed to resolve command line options\n' >&2
+				printf 'INTERNAL ERROR: Failed to resolve command line options\n' >&2
 				return 1
 				;;
 		esac
@@ -256,10 +256,10 @@ replicate() {
 	printf 'Retrieving data objects to replicate...\n' >&2
 
 	local maxCreateDate
-	maxCreateDate=$(date --iso-8601 --date "$age days ago")
+	maxCreateDate="$(date --iso-8601 --date "$age days ago")"
 
 	local maxCreateTime
-	maxCreateTime=$(date --date "$maxCreateDate" '+%s')
+	maxCreateTime="$(date --date "$maxCreateDate" '+%s')"
 
 	local resCond
 	if [[ -n "$srcResc" ]]
@@ -281,7 +281,7 @@ replicate() {
 	fi
 
 	local replQuery
-	replQuery=$(mk_repl_query "$maxCreateTime" "$baseCond" "$resCond")
+	replQuery="$(mk_repl_query "$maxCreateTime" "$baseCond" "$resCond")"
 
 	psql \
 			--no-align --tuples-only --record-separator-zero \
@@ -290,7 +290,7 @@ replicate() {
 		> "$objList"
 
 	local tot
-	tot=$(count < "$objList")
+	tot="$(count < "$objList")"
 	printf '%d data objects to replicate\n' "$tot" >&2
 
 	if [[ "$tot" -gt 0 ]]
@@ -300,67 +300,77 @@ replicate() {
 			local cnt=0
 
 			# Small non-zero byte files
-			cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 16 512 0 1 "$untilTS" \
-			  < "$objList")    # 16 1-threaded transfers
+			cnt="$(\
+				select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 16 512 0 1 "$untilTS" \
+			  		< "$objList" )"    # 16 1-threaded transfers
 
-      if [[ "$maxThreads" -ge 2 ]]
+      	if [[ "$maxThreads" -ge 2 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 8 128 1 2 "$untilTS" \
-				  < "$objList")  # 8 2-threaded
-      fi
+				cnt="$(\
+					select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 8 128 1 2 "$untilTS" \
+				  		< "$objList" )"  # 8 2-threaded
+      	fi
 
 			if [[ "$maxThreads" -ge 3 ]]
-      then
-				cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 6 72 2 3 "$untilTS" \
-					< "$objList")  # 6 3-threaded
+      	then
+				cnt="$(\
+					select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 6 72 2 3 "$untilTS" \
+						< "$objList" )"  # 6 3-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 5 ]]
-      then
-				cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 4 32 3 5 "$untilTS" \
-				  < "$objList")  # 4 4--5-threaded
+      	then
+				cnt="$(\
+					select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 4 32 3 5 "$untilTS" \
+						< "$objList" )"  # 4 4--5-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 7 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 3 18 5 7 "$untilTS" \
-				  < "$objList")  # 3 6--7-threaded
+				cnt="$(\
+					select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 3 18 5 7 "$untilTS" \
+						< "$objList" )"  # 3 6--7-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 15 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 2 8 7 15 "$untilTS" \
-				  < "$objList")  # 2 8--15-threaded
+				cnt="$(\
+					select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 2 8 7 15 "$untilTS" \
+						< "$objList" )"  # 2 8--15-threaded
 			fi
 
 			# Large file transfers
 			local minSize
-			minSize=$(threads_to_MB "$maxThreads")
+			minSize="$(threads_to_MB "$maxThreads")"
 
 			if [[ "$minSize" -lt 480 ]]
 			then
-				cnt=$(select_cohort_by_size \
-						"$cnt" \
-						"$tot" \
-						"$srcResc" \
-						"$destResc" \
-						"$procMult" \
-						"$maxThreads" \
-						"$untilTS" \
-						"$minSize" \
-						480 \
-					< "$objList")  # < 480 MiB transfers
+				cnt="$(\
+					select_cohort_by_size \
+							"$cnt" \
+							"$tot" \
+							"$srcResc" \
+							"$destResc" \
+							"$procMult" \
+							"$maxThreads" \
+							"$untilTS" \
+							"$minSize" \
+							480 \
+						< "$objList" )"  # < 480 MiB transfers
 			fi
 
-			cnt=$(select_cohort_by_size \
-					"$cnt" "$tot" "$srcResc" "$destResc" "$procMult" "$maxThreads" "$untilTS" 480 \
-				< "$objList")  # >= 480 MiB transfers
+			cnt="$(\
+				select_cohort_by_size \
+						"$cnt" "$tot" "$srcResc" "$destResc" "$procMult" "$maxThreads" "$untilTS" 480 \
+					< "$objList" )"  # >= 480 MiB transfers
 
 			# zero byte files
-			cnt=$(select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 16 512 0 0 "$untilTS" \
-			  < "$objList")  # 16 1-threaded transfers
+			cnt="$(\
+				select_cohort "$cnt" "$tot" "$srcResc" "$destResc" "$procMult" 16 512 0 0 "$untilTS" \
+					< "$objList" )"  # 16 1-threaded transfers
 		else
-			select_cohort 0 "$tot" "$srcResc" "$destResc" "$procMult" 16 2 -1 -1 "$untilTS" < "$objList" \
+			select_cohort 0 "$tot" "$srcResc" "$destResc" "$procMult" 16 2 -1 -1 "$untilTS" \
+				< "$objList" \
 				> /dev/null
 		fi
 	fi
@@ -369,11 +379,11 @@ replicate() {
 
 format_opts() {
 	local longOpts=(
-	  age: collection: help host: max-threads: multiplier: port: dest-resc: src-resc: until: user:
+		age: collection: help host: max-threads: multiplier: port: dest-resc: src-resc: until: user:
 		version)
 
 	local longOptsStr
-	longOptsStr=$(printf '%s\n' "${longOpts[@]}" | paste --serial --delimiter=,)
+	longOptsStr="$(printf '%s\n' "${longOpts[@]}" | paste --serial --delimiter=,)"
 	getopt --name "$EXEC_NAME" --longoptions "$longOptsStr" --options A:C:hH:M:N:P:R:S:u:U:v -- "$@"
 }
 
@@ -449,7 +459,7 @@ mk_prog_msg() {
 	local subTotal="$4"
 
 	printf 'cohort: %0*d/%d, all: %0*d/%d' \
-				 ${#subTotal} "$subCount" "$subTotal" ${#total} "$count" "$total"
+		${#subTotal} "$subCount" "$subTotal" ${#total} "$count" "$total"
 }
 
 
@@ -477,7 +487,7 @@ track_prog() {
 	local subCnt=0
 
 	local msg
-	msg=$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")
+	msg="$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")"
 
 	printf '%s' "$msg" >&2
 
@@ -488,13 +498,13 @@ track_prog() {
 			((subCnt++))
 			((cnt++))
 			printf '\r%*s\r' ${#msg} '' >&2
-			msg=$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")
+			msg="$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")"
 			printf '%s' "$msg" >&2
 		fi
 	done
 
 	printf '\r%*s\r' ${#msg} '' >&2
-	msg=$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")
+	msg="$(mk_prog_msg "$cnt" "$tot" "$subCnt" "$subTot")"
 	printf '%s\n' "$msg" >&2
 	printf '%s' "$cnt"
 }
@@ -535,17 +545,17 @@ select_cohort() {
 	then
 		minSizeMiB=0
 		minSizeB=1
-		maxSizeMiB=$(threads_to_MB "$maxThreads")
+		maxSizeMiB="$(threads_to_MB "$maxThreads")"
 		maxSizeB=$((maxSizeMiB * ((1024 ** 2))))
 	else
-		minSizeMiB=$(threads_to_MB "$minThreads")
+		minSizeMiB="$(threads_to_MB "$minThreads")"
 		minSizeB=$((minSizeMiB * ((1024 ** 2))))
-		maxSizeMiB=$(threads_to_MB "$maxThreads")
+		maxSizeMiB="$(threads_to_MB "$maxThreads")"
 		maxSizeB=$((maxSizeMiB * ((1024 ** 2))))
 	fi
 
 	local cohortList
-	cohortList=$(mktemp)
+	cohortList="$(mktemp)"
 
 	if [[ -n "$maxSizeB" ]]
 	then
@@ -555,7 +565,7 @@ select_cohort() {
 	fi > "$cohortList"
 
 	local subTotal
-	subTotal=$(count <"$cohortList")
+	subTotal="$(count <"$cohortList")"
 
 	if [[ "$minSizeMiB" -le 0 ]] && [[ -z "$maxSizeMiB" ]]
 	then
@@ -568,7 +578,7 @@ select_cohort() {
 		printf 'Replicating %s files with size in (0, %s) MiB\n' "$subTotal" "$maxSizeMiB"
 	else
 		printf 'Replicating %s files with size in [%s, %s) MiB\n' \
-					 "$subTotal" "$minSizeMiB" "$maxSizeMiB"
+			"$subTotal" "$minSizeMiB" "$maxSizeMiB"
 	fi >&2
 
 	if [[ "$subTotal" -gt 0 ]]
@@ -618,7 +628,7 @@ select_cohort_by_size() {
 	local maxSizeB=$((maxSizeMiB * 1024 ** 2))
 
 	local cohortList
-	cohortList=$(mktemp)
+	cohortList="$(mktemp)"
 
 	if [[ -n "$maxSizeMiB" ]]
 	then
@@ -629,12 +639,12 @@ select_cohort_by_size() {
 	fi > "$cohortList"
 
 	local subTotal
-	subTotal=$(count < "$cohortList")
+	subTotal="$(count < "$cohortList")"
 
 	if [[ -n "$maxSizeMiB" ]]
 	then
 		printf 'Replicating %s files with size in [%s, %s) MiB\n' \
-					 "$subTotal" "$minSizeMiB" "$maxSizeMiB" \
+				"$subTotal" "$minSizeMiB" "$maxSizeMiB" \
 			>&2
 	else
 		printf 'Replicating %s files with size >= %s MiB\n' "$subTotal" "$minSizeMiB" >&2
@@ -668,7 +678,7 @@ threads_to_MB() {
 REPL_BATCH() {
 	set -o errexit -o nounset -o pipefail
 
-  local srcResc="$1"
+	local srcResc="$1"
 	local destResc="$2"
 	local maxThreads="$3"
 	local untilTS="$4"
@@ -676,7 +686,7 @@ REPL_BATCH() {
 
 	CHECK_TIME "$untilTS"
 
-  local replArgs=(-B -M -T -v -N "$maxThreads")
+	local replArgs=(-B -M -T -v -N "$maxThreads")
 
 	if [[ -n "$destResc" ]]
 	then
