repl: moved streaming repl logic into own function

diff --git a/repl b/repl
--- a/repl
+++ b/repl
@@ -259,28 +259,157 @@ replicate() {
 		printf 'DEBUG: object list in %s\n' "$ObjCache" >&2
 	fi
 
-	local tot
-	tot="$(count < "$ObjCache")"
-	printf '%d data objects to replicate\n' "$tot" >&2
+	local totObjs
+	totObjs="$(count < "$ObjCache")"
+	printf '%d data objects to replicate\n' "$totObjs" >&2
 
-	if (( tot == 0 )); then
+	if (( totObjs == 0 )); then
 		return 0
 	fi
 
 	if (( maxTransThreads > 0 )); then
 		replicate_threaded \
-			"$maxTransThreads" "$procMult" "$srcResc" "$destResc" "$untilTS" "$tot" "$ObjCache"
+			"$maxTransThreads" "$procMult" "$srcResc" "$destResc" "$untilTS" "$totObjs" "$ObjCache"
 	else
-		# streaming replication
-		local maxProcs=$(( MAX_THREADS * procMult ))
-
-		local maxIreplArgs
-		maxIreplArgs="$(div_ceil "$MAX_DATA_OBJS_PER_IREPL" 100)"
-
-		select_cohort 0 "$tot" "$srcResc" "$destResc" "$maxProcs" "$maxIreplArgs" -1 "$untilTS" \
-			< "$ObjCache" \
-			> /dev/null
+		replicate_streaming "$procMult" "$srcResc" "$destResc" "$untilTS" "$totObjs" "$ObjCache"
 	fi
+}
+
+finish() {
+	local exitCode="$1"
+
+	if [[ -z "$DEBUG" && -n "${ObjCache-}" ]]; then
+		rm --force "$ObjCache"
+	fi
+
+	eval "exec 1>&$LOG $LOG>&-"
+
+	if (( exitCode == TIMEDOUT )); then
+		printf 'out of time\n' >&2
+		exit 0
+	fi
+
+	exit "$exitCode"
+}
+
+compute_until_timestamp() {
+	local until="$1"
+
+	if [[ -n "$until" ]]; then
+		if ! date --date="$until" '+%s'; then
+			printf 'until "%s" is not a valid date format\n' "$until" >&2
+			return 1
+		fi
+	fi
+}
+
+count() {
+	local tot=0
+
+	while read -r -d ''; do
+		: $(( tot++ ))
+	done
+
+	echo "$tot"
+}
+
+get_data_to_repl() {
+	local age="$1"
+	local srcResc="$2"
+	local destResc="$3"
+	local baseColl="$4"
+
+	printf 'Retrieving data objects to replicate...\n' >&2
+
+	local maxCreateTime
+	maxCreateTime="$(date --date="$(date --iso-8601 --date="$age days ago")" '+%s')"
+
+	local resCond
+	if [[ -n "$srcResc" ]]; then
+		resCond="$(mk_resc_cond "$srcResc")"
+	elif [[ -n "$destResc" ]]; then
+		resCond="$(mk_resc_cond "$destResc")"
+	else
+		resCond=TRUE
+	fi
+
+	local baseCond
+	if [[ -n "$baseColl" ]]; then
+		baseCond="c.coll_name = '$baseColl' OR c.coll_name LIKE '$baseColl/%'"
+	else
+		baseCond=TRUE
+	fi
+
+	local replQuery
+	replQuery="$(mk_repl_query "$maxCreateTime" "$baseCond" "$resCond")"
+
+	if ! \
+		psql \
+			--no-align --tuples-only --record-separator-zero \
+			--command "$replQuery" --field-separator ' ' \
+			ICAT
+	then
+		printf 'Failed to retrieve data objects\n' >&2
+		return 1
+	fi
+}
+
+# Redirect stdout to FD 3 to use as a logging channel
+prep_logging() {
+	eval "exec $LOG>&1"
+}
+
+validate_repl_conds() {
+	local procMult="$1"
+	local srcResc="$2"
+	local destResc="$3"
+	local untilTS="$4"
+
+	if [[ -n "$procMult" ]] && ! [[ "$procMult" =~ ^[1-9][0-9]* ]]; then
+		printf 'The multiplier must be a positive number. The given value was %s.\n' "$procMult" >&2
+		return 1
+	fi
+
+	if [[ -n "$destResc" && "$srcResc" == "$destResc" ]]; then
+		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
+		    "$destResc" "$srcResc" \
+			>&2
+
+		return 1
+	fi
+
+	if ! CHECK_TIME "$untilTS"; then
+		printf 'Stop time is in the past\n' >&2
+		return 1
+	fi
+
+	if ! iadmin lz &> /dev/null; then
+		printf "aren't authenticated as a rodsadmin user\n" >&2
+		return 1
+	fi
+
+	if ! psql ICAT <<<'' &> /dev/null; then
+		printf "aren't able to connect to the ICAT DB without a password\n" >&2
+		return 1
+	fi
+}
+
+replicate_streaming() {
+	local procMult="$1"
+	local srcResc="$2"
+	local destResc="$3"
+	local untilTS="$4"
+	local totObjs="$5"
+	local objCache="$6"
+
+	local maxProcs=$(( MAX_THREADS * procMult ))
+
+	local maxIreplArgs
+	maxIreplArgs="$(div_ceil "$MAX_DATA_OBJS_PER_IREPL" 100)"
+
+	select_cohort 0 "$totObjs" "$srcResc" "$destResc" "$maxProcs" "$maxIreplArgs" -1 "$untilTS" \
+		< "$objCache" \
+		> /dev/null
 }
 
 replicate_threaded() {
@@ -363,76 +492,6 @@ replicate_threaded() {
 	echo "$cnt"
 }
 
-
-finish() {
-	local exitCode="$1"
-
-	if [[ -z "$DEBUG" && -n "${ObjCache-}" ]]; then
-		rm --force "$ObjCache"
-	fi
-
-	eval "exec 1>&$LOG $LOG>&-"
-
-	if (( exitCode == TIMEDOUT )); then
-		printf 'out of time\n' >&2
-		exit 0
-	fi
-
-	exit "$exitCode"
-}
-
-compute_until_timestamp() {
-	local until="$1"
-
-	if [[ -n "$until" ]]; then
-		if ! date --date="$until" '+%s'; then
-			printf 'until "%s" is not a valid date format\n' "$until" >&2
-			return 1
-		fi
-	fi
-}
-
-get_data_to_repl() {
-	local age="$1"
-	local srcResc="$2"
-	local destResc="$3"
-	local baseColl="$4"
-
-	printf 'Retrieving data objects to replicate...\n' >&2
-
-	local maxCreateTime
-	maxCreateTime="$(date --date="$(date --iso-8601 --date="$age days ago")" '+%s')"
-
-	local resCond
-	if [[ -n "$srcResc" ]]; then
-		resCond="$(mk_resc_cond "$srcResc")"
-	elif [[ -n "$destResc" ]]; then
-		resCond="$(mk_resc_cond "$destResc")"
-	else
-		resCond=TRUE
-	fi
-
-	local baseCond
-	if [[ -n "$baseColl" ]]; then
-		baseCond="c.coll_name = '$baseColl' OR c.coll_name LIKE '$baseColl/%'"
-	else
-		baseCond=TRUE
-	fi
-
-	local replQuery
-	replQuery="$(mk_repl_query "$maxCreateTime" "$baseCond" "$resCond")"
-
-	if ! \
-		psql \
-			--no-align --tuples-only --record-separator-zero \
-			--command "$replQuery" --field-separator ' ' \
-			ICAT
-	then
-		printf 'Failed to retrieve data objects\n' >&2
-		return 1
-	fi
-}
-
 mk_repl_query() {
 	local maxTime="$1"
 	local baseCond="$2"
@@ -471,11 +530,6 @@ max_args_per_irepl() {
 	local threadsPerDataObj="$1"
 
 	div_ceil "$MAX_DATA_OBJS_PER_IREPL" $(( threadsPerDataObj * threadsPerDataObj ))
-}
-
-# Redirect stdout to FD 3 to use as a logging channel
-prep_logging() {
-	eval "exec $LOG>&1"
 }
 
 select_cohort() {
@@ -608,51 +662,6 @@ select_cohort_by_size() {
 	fi
 
 	rm --force "$cohortList"
-}
-
-validate_repl_conds() {
-	local procMult="$1"
-	local srcResc="$2"
-	local destResc="$3"
-	local untilTS="$4"
-
-	if [[ -n "$procMult" ]] && ! [[ "$procMult" =~ ^[1-9][0-9]* ]]; then
-		printf 'The multiplier must be a positive number. The given value was %s.\n' "$procMult" >&2
-		return 1
-	fi
-
-	if [[ -n "$destResc" && "$srcResc" == "$destResc" ]]; then
-		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
-		    "$destResc" "$srcResc" \
-			>&2
-
-		return 1
-	fi
-
-	if ! CHECK_TIME "$untilTS"; then
-		printf 'Stop time is in the past\n' >&2
-		return 1
-	fi
-
-	if ! iadmin lz &> /dev/null; then
-		printf "aren't authenticated as a rodsadmin user\n" >&2
-		return 1
-	fi
-
-	if ! psql ICAT <<<'' &> /dev/null; then
-		printf "aren't able to connect to the ICAT DB without a password\n" >&2
-		return 1
-	fi
-}
-
-count() {
-	local tot=0
-
-	while read -r -d ''; do
-		: $(( tot++ ))
-	done
-
-	echo "$tot"
 }
 
 disp_cohort_info() {
