repl: moved remaining repl logic from main to replicate

diff --git a/repl b/repl
--- a/repl
+++ b/repl
@@ -95,72 +95,18 @@ main() {
 
 	if [[ -n "${optMap[help]}" ]]; then
 		show_help
-		return 0
-	fi
-
-	if [[ -n "${optMap[version]}" ]]; then
+	elif [[ -n "${optMap[version]}" ]]; then
 		printf '%s\n' "$VERSION"
-		return 0
+	else
+		replicate \
+			"${optMap[age]}"  \
+			"${optMap[max-threads]}" \
+			"${optMap[multiplier]}" \
+			"${optMap[collection]}" \
+			"${optMap[src-resc]}" \
+			"${optMap[dest-resc]}" \
+			"${optMap[until]}"
 	fi
-
-	if [[ -n "${optMap[multiplier]}" ]]; then
-		if ! [[ "${optMap[multiplier]}" =~ ^[1-9][0-9]* ]]; then
-			printf 'The multiplier must be a positive number. The given value was %s.\n' \
-			    "${optMap[multiplier]}" \
-				>&2
-
-			return 1
-		fi
-	fi
-
-	if [[ -n "${optMap[dest-resc]}" && "${optMap[src-resc]}" == "${optMap[dest-resc]}" ]]; then
-		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
-		    "${optMap[dest-resc]}" "${optMap[src-resc]}" \
-			>&2
-
-		return 1
-	fi
-
-	local untilTS
-	if [[ -n "${optMap[until]}" ]]; then
-		if ! untilTS="$(date --date="${optMap[until]}" '+%s')"; then
-			printf '"%s" is not a valid date format\n' "${optMap[until]}"
-			return 1
-		fi
-	fi
-
-	# Redirect stdout to FD 3 to use as a logging channel
-	eval "exec $LOG>&1"
-
-	local objList
-	objList="$(mktemp)"
-
-	trap 'finish "$?" '"'$objList'" EXIT
-
-	if ! iadmin lz &> /dev/null; then
-		printf "aren't authenticated as a rodsadmin user\n" >&2
-		return 1
-	fi
-
-	if ! psql ICAT <<<'' &> /dev/null; then
-		printf "aren't able to connect to the ICAT DB without a password\n" >&2
-		return 1
-	fi
-
-	if ! CHECK_TIME "${untilTS-}"; then
-	 printf 'Stop time is in the past\n' >&2
-	 return 1
-	fi
-
-  replicate \
-		"$objList" \
-		"${optMap[age]}"  \
-		"${optMap[max-threads]}" \
-		"${optMap[multiplier]}" \
-		"${optMap[collection]}" \
-		"${optMap[src-resc]}" \
-		"${optMap[dest-resc]}" \
-		"${untilTS-}"
 }
 
 
@@ -239,14 +185,61 @@ resolve_opts() {
 
 
 replicate() {
-	local objList="$1"
-	local age="$2"
-	local maxThreads="$3"
-	local procMult="$4"
-	local baseColl="$5"
-	local srcResc="$6"
-	local destResc="$7"
-	local untilTS="$8"
+	local age="$1"
+	local maxThreads="$2"
+	local procMult="$3"
+	local baseColl="$4"
+	local srcResc="$5"
+	local destResc="$6"
+	local until="$7"
+
+	if [[ -n "$procMult" ]]; then
+		if ! [[ "$procMult" =~ ^[1-9][0-9]* ]]; then
+			printf 'The multiplier must be a positive number. The given value was %s.\n' "$procMult" \
+				>&2
+
+			return 1
+		fi
+	fi
+
+	if [[ -n "$destResc" && "$srcResc" == "$destResc" ]]; then
+		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
+		    "$destResc" "$srcResc" \
+			>&2
+
+		return 1
+	fi
+
+	local untilTS=
+	if [[ -n "$until" ]]; then
+		if ! untilTS="$(date --date="$until" '+%s')"; then
+			printf '"%s" is not a valid date format\n' "$until"
+			return 1
+		fi
+	fi
+
+	# Redirect stdout to FD 3 to use as a logging channel
+	eval "exec $LOG>&1"
+
+	local objList
+	objList="$(mktemp)"
+
+	trap 'finish "$?" '"'$objList'" EXIT
+
+	if ! iadmin lz &> /dev/null; then
+		printf "aren't authenticated as a rodsadmin user\n" >&2
+		return 1
+	fi
+
+	if ! psql ICAT <<<'' &> /dev/null; then
+		printf "aren't able to connect to the ICAT DB without a password\n" >&2
+		return 1
+	fi
+
+	if ! CHECK_TIME "$untilTS"; then
+	 printf 'Stop time is in the past\n' >&2
+	 return 1
+	fi
 
 	printf 'Retrieving data objects to replicate...\n' >&2
 
