repl: made destination resource optional
The destination resource was made optional. If it is not provided, the
default destination resource will be used.

diff --git a/repl b/repl
--- a/repl
+++ b/repl
@@ -25,8 +25,8 @@ Options:
                               once, default: 1
  -P, --port PORT              connect to the ICAT's DBMS listening on TCP port
                               PORT instead of the PostgreSQL default
- -R, --dest-resc DEST-RESC    REQUIRED - replicate data objects to resource
-                              DEST-RESC
+ -R, --dest-resc DEST-RESC    replicate data objects to resource DEST-RESC
+                              instead of default replication resource
  -S, --src-resc SRC-RESC      only replicate the data objects with a file on the
                               resource SRC-RESC
  -u, --until STOP-TIME        the time to stop replication in a format
@@ -148,13 +148,6 @@ main()
 		esac
 	done
 
-  if [[ -z "${destResc-}" ]]
-	then
-		printf 'The -R|--dest-resc option is required\n' >&2
-		show_help >&2
-		return 1
-	fi
-
 	if [[ -n "$procMult" ]]
 	then
 		if ! [[ "$procMult" =~ ^[1-9][0-9]* ]]
@@ -162,6 +155,14 @@ main()
 			printf 'The multiplier must be a positive number. The given value was %s.\n' "$procMult" >&2
 			exit 1
 		fi
+	fi
+
+  if [[ -n "${destResc-}" && "$srcResc" == "$destResc" ]]
+	then
+		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
+		    "$destResc" "$srcResc" \
+			>&2
+		return 1
 	fi
 
 	local untilTS=
@@ -180,7 +181,6 @@ main()
 	local objList
 	objList=$(mktemp)
 
-	#shellcheck disable=SC2064
 	trap 'finish "$?" '"'$objList'" EXIT
 
 	if ! iadmin lz &> /dev/null
@@ -213,8 +213,11 @@ main()
 	if [[ -n "$srcResc" ]]
 	then
 		resCond="d.resc_name = '$srcResc'"
-	else
+	elif [[ -n "${destResc-}" ]]
+	then
 		resCond="d.resc_name != '$destResc'"
+	else
+		resCond=TRUE
 	fi
 
 	local baseCond
@@ -245,31 +248,37 @@ main()
 			local cnt=0
 
 			# Small non-zero byte files
-			cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult" 16 512 0 1 "$untilTS" < "$objList")  # 16 1-threaded transfers
+			cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult" 16 512 0 1 "$untilTS" \
+			  < "$objList")    # 16 1-threaded transfers
 
       if [[ "$maxThreads" -ge 2 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult"  8 128 1 2 "$untilTS" < "$objList")  # 8 2-threaded
+				cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult"  8 128 1 2 "$untilTS" \
+				  < "$objList")  # 8 2-threaded
       fi
 
 			if [[ "$maxThreads" -ge 3 ]]
       then
-				cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult"  6  72 2 3 "$untilTS" < "$objList")  # 6 3-threaded
+				cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult"  6  72 2 3 "$untilTS" \
+					< "$objList")  # 6 3-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 5 ]]
       then
-				cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult"  4  32 3 5 "$untilTS" < "$objList")  # 4 4--5-threaded
+				cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult"  4  32 3 5 "$untilTS" \
+				  < "$objList")  # 4 4--5-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 7 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult"  3  18 5 7 "$untilTS" < "$objList")  # 3 6--7-threaded
+				cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult"  3  18 5 7 "$untilTS" \
+				  < "$objList")  # 3 6--7-threaded
 			fi
 
 			if [[ "$maxThreads" -ge 15 ]]
 			then
-				cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult"  2   8 7 15 "$untilTS" < "$objList")  # 2 8--15-threaded
+				cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult"  2   8 7 15 "$untilTS" \
+				  < "$objList")  # 2 8--15-threaded
 			fi
 
 			# Large file transfers
@@ -278,15 +287,21 @@ main()
 
 			if [[ "$minSize" -lt 480 ]]
 			then
-				cnt=$(select_cohort_by_size "$cnt" "$tot" "$destResc" "$procMult" "$maxThreads" "$untilTS" "$minSize" 480 < "$objList")  # < 480 MiB transfers
+				cnt=$(select_cohort_by_size \
+						"$cnt" "$tot" "${destResc-}" "$procMult" "$maxThreads" "$untilTS" "$minSize" 480 \
+					< "$objList")  # < 480 MiB transfers
 			fi
 
-			cnt=$(select_cohort_by_size "$cnt" "$tot" "$destResc" "$procMult" "$maxThreads" "$untilTS" 480 < "$objList")  # >= 480 MiB transfers
+			cnt=$(select_cohort_by_size \
+					"$cnt" "$tot" "${destResc-}" "$procMult" "$maxThreads" "$untilTS" 480 \
+				< "$objList")  # >= 480 MiB transfers
 
 			# zero byte files
-			cnt=$(select_cohort "$cnt" "$tot" "$destResc" "$procMult" 16 512 0 0 "$untilTS" < "$objList")  # 16 1-threaded transfers
+			cnt=$(select_cohort "$cnt" "$tot" "${destResc-}" "$procMult" 16 512 0 0 "$untilTS" \
+			  < "$objList")  # 16 1-threaded transfers
 		else
-			select_cohort 0 "$tot" "$destResc" "$procMult" 16 2 -1 -1 "$untilTS" < "$objList" > /dev/null
+			select_cohort 0 "$tot" "${destResc-}" "$procMult" 16 2 -1 -1 "$untilTS" < "$objList" \
+			  > /dev/null
 		fi
 	fi
 }
@@ -605,7 +620,12 @@ REPL_BATCH()
 	CHECK_TIME "$untilTS"
 
 	local replStatus=0
-	irepl -B -M -T -v -N "$maxThreads" -R "$destResc" "$@" || replStatus="$?"
+	if [[ -n "$destResc" ]]
+	then
+	  irepl -B -M -T -v -N "$maxThreads" -R "$destResc" "$@" || replStatus="$?"
+  else
+		irepl -B -M -T -v -N "$maxThreads" "$@" || replStatus="$?"
+	fi
 
 	# TODO: Trying to figure out the irepl error code for when irepl logs a
 	# '_rcConnect: connectToRhost error, server on data.cyverse.org:1247 is
